import {
  IProject,
  ProgrammingTechologyName,
  ProjectLinkType,
  ProjectResponsibility,
} from "../../models/IProject";

export const PROJECTS_PREDEFINED_DATA: IProject[] = [
  {
    name: "AnimaAI",
    teamAmount: "8",
    mainFeatures: [
      "Smart AI chat for conversations",
      "React Native for 3 platforms: Android, iOS, Web",
      "Monorepo Architecture for supporting a lot of apps from one repo",
      "Best-optimised lists for all platforms",
      "A lot of smooth interactive animations",
      "Different message possibilities including audio messages",
      "Gamification with awards, rewards and XP system",
    ],
    responsibilities: [
      ProjectResponsibility.Architecture,
      ProjectResponsibility.CodeReview,
      ProjectResponsibility.TestsCoverage,
      ProjectResponsibility.Documentation,
      ProjectResponsibility.Development,
      ProjectResponsibility.Support,
      ProjectResponsibility.CustomerCommunication,
    ],
    technologies: [
      ProgrammingTechologyName.ReactNative,
      ProgrammingTechologyName.ReactNativeWeb,
      ProgrammingTechologyName.TypeScript,
      ProgrammingTechologyName.ReactNavigation,
      ProgrammingTechologyName.Redux,
      ProgrammingTechologyName.ReduxSaga,
      ProgrammingTechologyName.ReduxPersist,
      ProgrammingTechologyName.Reactotron,
      ProgrammingTechologyName.LottieAnimation,
      ProgrammingTechologyName.Bitrise,
      ProgrammingTechologyName.Context,
      ProgrammingTechologyName.Jest,
      ProgrammingTechologyName.I18n,
      ProgrammingTechologyName.Flipper,
      ProgrammingTechologyName.AmplitudeAnalytic,
      ProgrammingTechologyName.Axios,
      ProgrammingTechologyName.StripeIAP,
    ],
    appLinks: [
      {
        type: ProjectLinkType.IOS,
        appLink: "https://apps.apple.com/app/anima-ai-friend-virtual-chat/id1537239242",
      },
      {
        type: ProjectLinkType.Android,
        appLink:
          "https://play.google.com/store/apps/details?id=anima.virtual.ai.robot.friend&hl=en_US",
      },
      {
        type: ProjectLinkType.Web,
        appLink: "https://myanima.ai/",
      },
    ],
  },

  {
    name: "MatchaAI",
    teamAmount: "12",
    mainFeatures: [
      "Smart AI chat for conversations",
      "React Native for 2 platforms: Android, iOS",
      "Monorepo Architecture for supporting a lot of apps from one repo",
      "Best-optimised lists for all platforms",
      "A lot of smooth interactive animations",
      "Different message possibilities including audio messages",
      "Strong analytic and logging system",
    ],
    responsibilities: [
      ProjectResponsibility.Architecture,
      ProjectResponsibility.CodeReview,
      ProjectResponsibility.TestsCoverage,
      ProjectResponsibility.Documentation,
      ProjectResponsibility.Development,
      ProjectResponsibility.Support,
      ProjectResponsibility.CustomerCommunication,
    ],
    technologies: [
      ProgrammingTechologyName.ReactNative,
      ProgrammingTechologyName.TypeScript,
      ProgrammingTechologyName.ReactNavigation,
      ProgrammingTechologyName.Redux,
      ProgrammingTechologyName.ReduxSaga,
      ProgrammingTechologyName.ReduxPersist,
      ProgrammingTechologyName.LottieAnimation,
      ProgrammingTechologyName.Bitrise,
      ProgrammingTechologyName.I18n,
      ProgrammingTechologyName.Flipper,
      ProgrammingTechologyName.AmplitudeAnalytic,
      ProgrammingTechologyName.Axios,
    ],
    appLinks: [
      {
        type: ProjectLinkType.IOS,
        appLink: "https://apps.apple.com/in/app/matcha-character-ai-chat-bot/id6455986674",
      },
      {
        type: ProjectLinkType.Android,
        appLink:
          "https://play.google.com/store/apps/details?id=ai.character.chat.bots.matcha.app&hl=en_US",
      },
    ],
  },

  {
    name: "CitizenRemote",
    teamAmount: "14",
    mainFeatures: [
      "Secure live chat with Socket.IO connection",
      "Image, video, PDFs uploading to S3",
      "Sharing through Firebase Dynamic Links",
      "Social media login",
      "Firebase Analytic",
      "Awesome smooth animations",
      "Strong typing with TypeScript",
      "Fastlane Build Automation",
    ],
    responsibilities: [
      ProjectResponsibility.Architecture,
      ProjectResponsibility.CodeReview,
      ProjectResponsibility.CustomerCommunication,
      ProjectResponsibility.Deploy,
      ProjectResponsibility.Documentation,
      ProjectResponsibility.Mentoring,
      ProjectResponsibility.TeamLeading,
    ],
    technologies: [
      ProgrammingTechologyName.ReactNative,
      ProgrammingTechologyName.TypeScript,
      ProgrammingTechologyName.ReactNavigation,
      ProgrammingTechologyName.Redux,
      ProgrammingTechologyName.ReduxPersist,
      ProgrammingTechologyName.ReduxSaga,
      ProgrammingTechologyName.WebSockets,
      ProgrammingTechologyName.Reactotron,
      ProgrammingTechologyName.Axios,
      ProgrammingTechologyName.FormikYup,
      ProgrammingTechologyName.I18n,
      ProgrammingTechologyName.Fastlane,
      ProgrammingTechologyName.FirebaseAnalytic,
      ProgrammingTechologyName.FirebaseAuth,
    ],
    appLinks: [
      {
        type: ProjectLinkType.IOS,
        appLink: "https://apps.apple.com/gb/app/citizen-remote/id1619297937",
      },
      {
        type: ProjectLinkType.Android,
        appLink: "https://play.google.com/store/apps/details?id=com.citizenremote&hl=en_GB&gl=US",
      },
    ],
  },

  {
    name: "Klarstein",
    teamAmount: "8",
    mainFeatures: [
      "Comprehensive smart home app",
      "Native modules for iOS and Android apps",
      "Own native library",
      "Well-encrypted API calls",
      "Invites through deeplinking",
      "Social media login",
    ],
    responsibilities: [
      ProjectResponsibility.Development,
      ProjectResponsibility.NativeModules,
      ProjectResponsibility.Support,
      ProjectResponsibility.Documentation,
      ProjectResponsibility.TestsCoverage,
      ProjectResponsibility.Deploy,
      ProjectResponsibility.CodeReview,
      ProjectResponsibility.Mentoring,
      ProjectResponsibility.CustomerCommunication,
    ],
    technologies: [
      ProgrammingTechologyName.ReactNative,
      ProgrammingTechologyName.TypeScript,
      ProgrammingTechologyName.ObjectiveC,
      ProgrammingTechologyName.Java,
      ProgrammingTechologyName.Redux,
      ProgrammingTechologyName.ReduxPersist,
      ProgrammingTechologyName.ReduxSaga,
      ProgrammingTechologyName.ReactNavigation,
      ProgrammingTechologyName.Reactotron,
      ProgrammingTechologyName.Axios,
      ProgrammingTechologyName.WebSockets,
      ProgrammingTechologyName.FirebaseAnalytic,
      ProgrammingTechologyName.FirebaseAuth,
      ProgrammingTechologyName.I18n,
      ProgrammingTechologyName.CircleCI,
    ],
    appLinks: [
      {
        type: ProjectLinkType.IOS,
        appLink: "https://apps.apple.com/us/app/klarstein/id1479571307",
      },
    ],
  },

  {
    name: "Loop Flow Messenger",
    teamAmount: "3",
    mainFeatures: [
      "Monorepo Architecture",
      "Shared module across all three apps",
      "Real-time chat",
      "Deeplinking",
      "Optimised lists with boosted speed for iOS & Android",
      "Firebase Reative Socket Pagination",
      "Social media login",
    ],
    responsibilities: [
      ProjectResponsibility.Architecture,
      ProjectResponsibility.Development,
      ProjectResponsibility.Support,
      ProjectResponsibility.Documentation,
      ProjectResponsibility.Deploy,
      ProjectResponsibility.TeamLeading,
      ProjectResponsibility.CodeReview,
      ProjectResponsibility.Mentoring,
      ProjectResponsibility.CustomerCommunication,
    ],
    technologies: [
      ProgrammingTechologyName.React,
      ProgrammingTechologyName.ReactExtension,
      ProgrammingTechologyName.ReactNative,
      ProgrammingTechologyName.TypeScript,
      ProgrammingTechologyName.Lerna,
      ProgrammingTechologyName.Redux,
      ProgrammingTechologyName.ReduxSaga,
      ProgrammingTechologyName.ReduxPersist,
      ProgrammingTechologyName.ReactNavigation,
      ProgrammingTechologyName.Reactotron,
      ProgrammingTechologyName.Axios,
      ProgrammingTechologyName.FirebaseAuth,
      ProgrammingTechologyName.FormikYup,
      ProgrammingTechologyName.I18n,
      ProgrammingTechologyName.WebSockets,
      ProgrammingTechologyName.Fastlane,
    ],
    appLinks: [
      {
        type: ProjectLinkType.IOS,
        appLink: "https://apps.apple.com/ie/app/loop-flow-messenger/id1541000589",
      },
    ],
  },

  {
    name: "Truevo Business",
    teamAmount: "4",
    mainFeatures: [
      "Secure screen with TouchID / FaceID",
      "A lot of interactable elements",
      "Strong banking encryption",
    ],
    responsibilities: [
      ProjectResponsibility.Development,
      ProjectResponsibility.Support,
      ProjectResponsibility.Mentoring,
      ProjectResponsibility.CodeReview,
      ProjectResponsibility.CustomerCommunication,
    ],
    technologies: [
      ProgrammingTechologyName.ReactNative,
      ProgrammingTechologyName.TypeScript,
      ProgrammingTechologyName.Redux,
      ProgrammingTechologyName.ReduxSaga,
      ProgrammingTechologyName.ReduxPersist,
      ProgrammingTechologyName.ReactNavigation,
      ProgrammingTechologyName.Reactotron,
      ProgrammingTechologyName.Axios,
      ProgrammingTechologyName.I18n,
      ProgrammingTechologyName.FormikYup,
      ProgrammingTechologyName.Fastlane,
    ],
    appLinks: [
      {
        type: ProjectLinkType.IOS,
        appLink: "https://apps.apple.com/za/app/truevo-business/id1511523105",
      },
    ],
  },

  {
    name: "Keyri",
    teamAmount: "3",
    mainFeatures: [
      "YCombinator startup",
      "Strong authorization encryption",
      "Deeplinking",
      "Secure screen with FaceID/TouchID",
      "Smooth animations",
    ],
    responsibilities: [ProjectResponsibility.Development, ProjectResponsibility.Support],
    technologies: [
      ProgrammingTechologyName.ReactNative,
      ProgrammingTechologyName.TypeScript,
      ProgrammingTechologyName.Redux,
      ProgrammingTechologyName.ReduxSaga,
      ProgrammingTechologyName.ReduxPersist,
      ProgrammingTechologyName.ReactNavigation,
      ProgrammingTechologyName.Reactotron,
      ProgrammingTechologyName.Fastlane,
    ],
    appLinks: [
      {
        type: ProjectLinkType.IOS,
        appLink: "https://apps.apple.com/ua/app/keyri/id1514738138",
      },
    ],
  },

  {
    name: "OnFire Messenger",
    teamAmount: "3",
    mainFeatures: [
      "Amazing smooth animations",
      "Real-time chat based on WebSockets architecture",
      "Sync calendar with the native OS calendar events",
      "Tabs & Drawer navigation",
      "Voice & Video chat",
      "Sharing media items",
      "Firebase Reactive Socket Pagination",
    ],
    responsibilities: [
      ProjectResponsibility.Development,
      ProjectResponsibility.Support,
      ProjectResponsibility.Deploy,
      ProjectResponsibility.CustomerCommunication,
    ],
    technologies: [
      ProgrammingTechologyName.ReactNative,
      ProgrammingTechologyName.Redux,
      ProgrammingTechologyName.ReduxSaga,
      ProgrammingTechologyName.ReduxPersist,
      ProgrammingTechologyName.ReactNavigation,
      ProgrammingTechologyName.FirebaseAuth,
      ProgrammingTechologyName.WebSockets,
      ProgrammingTechologyName.Fastlane,
    ],
    appLinks: [
      {
        type: ProjectLinkType.IOS,
        appLink: "https://apps.apple.com/ca/app/onfire-messenger/id1481054417",
      },
    ],
  },

  {
    name: "GoHeja",
    teamAmount: "3",
    mainFeatures: ["Animated calendar", "Dynamic map", "Real-time chat", "Split screen", "Charts"],
    responsibilities: [
      ProjectResponsibility.Architecture,
      ProjectResponsibility.Development,
      ProjectResponsibility.Support,
      ProjectResponsibility.Deploy,
      ProjectResponsibility.CustomerCommunication,
    ],
    technologies: [
      ProgrammingTechologyName.ReactNative,
      ProgrammingTechologyName.Redux,
      ProgrammingTechologyName.ReduxSaga,
      ProgrammingTechologyName.ReduxPersist,
      ProgrammingTechologyName.ReactNavigation,
      ProgrammingTechologyName.Reactotron,
      ProgrammingTechologyName.Axios,
      ProgrammingTechologyName.Mapbox,
      ProgrammingTechologyName.ChartsWrapper,
      ProgrammingTechologyName.I18n,
      ProgrammingTechologyName.WebSockets,
      ProgrammingTechologyName.Fastlane,
    ],
    appLinks: [
      {
        type: ProjectLinkType.IOS,
        appLink: "https://apps.apple.com/us/app/goheja/id1488438214?l=uk",
      },
    ],
  },

  {
    name: "Jesus Experience",
    teamAmount: "1",
    mainFeatures: ["Apple TV & iPad support", "Videos with bookmarks", "Amazing carousels"],
    responsibilities: [
      ProjectResponsibility.Development,
      ProjectResponsibility.Support,
      ProjectResponsibility.TestsCoverage,
      ProjectResponsibility.Deploy,
      ProjectResponsibility.CustomerCommunication,
    ],
    technologies: [
      ProgrammingTechologyName.ReactNative,
      ProgrammingTechologyName.Redux,
      ProgrammingTechologyName.ReduxSaga,
      ProgrammingTechologyName.ReduxPersist,
      ProgrammingTechologyName.ReactNavigation,
      ProgrammingTechologyName.RNDebugger,
      ProgrammingTechologyName.Axios,
    ],
    appLinks: [
      {
        type: ProjectLinkType.IOS,
        appLink: "https://apps.apple.com/us/app/experience-jesus/id1271102213",
      },
    ],
  },

  {
    name: "MIT: CredWallet",
    teamAmount: "1",
    mainFeatures: [
      "Full local app with strong encryption",
      "Amazing education credentials by QRCodes scanning",
      "Backups",
    ],
    responsibilities: [
      ProjectResponsibility.Architecture,
      ProjectResponsibility.Development,
      ProjectResponsibility.Support,
      ProjectResponsibility.Documentation,
      ProjectResponsibility.CustomerCommunication,
    ],
    technologies: [
      ProgrammingTechologyName.ReactNative,
      ProgrammingTechologyName.TypeScript,
      ProgrammingTechologyName.Redux,
      ProgrammingTechologyName.ReduxSaga,
      ProgrammingTechologyName.ReduxPersist,
      ProgrammingTechologyName.ReactNavigation,
      ProgrammingTechologyName.Reactotron,
      ProgrammingTechologyName.Axios,
      ProgrammingTechologyName.I18n,
      ProgrammingTechologyName.FormikYup,
    ],
    appLinks: [
      {
        type: ProjectLinkType.Web,
        appLink: "https://github.com/digitalcredentials/cred-wallet",
      },
    ],
  },

  {
    // BeatTheMarket
    name: "NDA",
    teamAmount: "2",
    mainFeatures: [
      "Real-time auction",
      "Live chart",
      "Shares statistics",
      "GraphQL communication",
      "Social media login",
    ],
    responsibilities: [
      ProjectResponsibility.Architecture,
      ProjectResponsibility.Development,
      ProjectResponsibility.Deploy,
      ProjectResponsibility.CustomerCommunication,
    ],
    technologies: [
      ProgrammingTechologyName.ReactNative,
      ProgrammingTechologyName.ReactNativeWeb,
      ProgrammingTechologyName.TypeScript,
      ProgrammingTechologyName.Context,
      ProgrammingTechologyName.GraphQL,
      ProgrammingTechologyName.ReactNavigation,
      ProgrammingTechologyName.Reactotron,
      ProgrammingTechologyName.FirebaseAuth,
      ProgrammingTechologyName.StripeIAP,
      ProgrammingTechologyName.VictoryCharts,
      ProgrammingTechologyName.Fastlane,
    ],
  },

  {
    // MasterHealth
    name: "NDA",
    teamAmount: "11",
    mainFeatures: [
      "Amazing habit-matching for every user by Sign Up process",
      "Comprehensive Amplitude analytic",
      "Awesome animations",
      "Events Calendar",
    ],
    responsibilities: [
      ProjectResponsibility.Development,
      ProjectResponsibility.Support,
      ProjectResponsibility.Documentation,
      ProjectResponsibility.CustomerCommunication,
    ],
    technologies: [
      ProgrammingTechologyName.ReactNative,
      ProgrammingTechologyName.TypeScript,
      ProgrammingTechologyName.Redux,
      ProgrammingTechologyName.ReduxSaga,
      ProgrammingTechologyName.ReduxPersist,
      ProgrammingTechologyName.ReactNavigation,
      ProgrammingTechologyName.AmplitudeAnalytic,
      ProgrammingTechologyName.FirebaseAuth,
      ProgrammingTechologyName.I18n,
      ProgrammingTechologyName.Jest,
      ProgrammingTechologyName.Flipper,
      ProgrammingTechologyName.Bitrise,
    ],
  },

  {
    // Sarafun
    name: "NDA",
    teamAmount: "4",
    mainFeatures: [
      "Invites through deeplinking",
      "Social media login",
      "Awesome smooth animations",
      "Optimised lists for both iOS and Android",
    ],
    responsibilities: [
      ProjectResponsibility.Architecture,
      ProjectResponsibility.CodeReview,
      ProjectResponsibility.CustomerCommunication,
      ProjectResponsibility.Deploy,
      ProjectResponsibility.Documentation,
      ProjectResponsibility.Mentoring,
      ProjectResponsibility.TeamLeading,
    ],
    technologies: [
      ProgrammingTechologyName.ReactNative,
      ProgrammingTechologyName.TypeScript,
      ProgrammingTechologyName.ReactNavigation,
      ProgrammingTechologyName.Redux,
      ProgrammingTechologyName.ReduxPersist,
      ProgrammingTechologyName.ReduxSaga,
      ProgrammingTechologyName.Reactotron,
      ProgrammingTechologyName.Axios,
      ProgrammingTechologyName.FormikYup,
      ProgrammingTechologyName.I18n,
      ProgrammingTechologyName.Fastlane,
    ],
  },
  {
    // Safer Place
    name: "NDA",
    teamAmount: "10",
    mainFeatures: [
      "Complex system - React Native / Firebase / DatoCMS",
      "Game for children with a lot of animations & sounds",
      "Awesome smooth animations",
      "Dynamic navigation building from CMS",
      "Dynamic cached translations from CMS",
      "A lot of gamification for better UX",
    ],
    responsibilities: [
      ProjectResponsibility.Architecture,
      ProjectResponsibility.CodeReview,
      ProjectResponsibility.CustomerCommunication,
      ProjectResponsibility.Deploy,
      ProjectResponsibility.Documentation,
      ProjectResponsibility.Mentoring,
      ProjectResponsibility.TeamLeading,
    ],
    technologies: [
      ProgrammingTechologyName.ReactNative,
      ProgrammingTechologyName.TypeScript,
      ProgrammingTechologyName.ReactNavigation,
      ProgrammingTechologyName.Redux,
      ProgrammingTechologyName.ReduxPersist,
      ProgrammingTechologyName.ReduxSaga,
      ProgrammingTechologyName.Reactotron,
      ProgrammingTechologyName.Axios,
      ProgrammingTechologyName.FormikYup,
      ProgrammingTechologyName.I18n,
      ProgrammingTechologyName.Fastlane,
    ],
  },
];
