import { COLORS } from "./colors";
import { ITheme } from "./themes.interface";

export const LIGHT_THEME: ITheme = {
  PRIMARY: COLORS.ALMOST_WHITE,
  PRIMARY_ADDITIONAL: COLORS.JUNGLE_GREEN,
  PRIMARY_TEXT: COLORS.JUNGLE_GREEN,
  SECONDARY: COLORS.ALMOST_BLACK,
  SECONDARY_ADDITIONAL: COLORS.GRAY,
  SECONDARY_TEXT: COLORS.ALMOST_WHITE,
};

export const DARK_THEME: ITheme = {
  PRIMARY: COLORS.ALMOST_BLACK,
  PRIMARY_ADDITIONAL: COLORS.BRIGHT_TURQUOISE,
  PRIMARY_TEXT: COLORS.BRIGHT_TURQUOISE,
  SECONDARY: COLORS.OYSTER_BAY,
  SECONDARY_ADDITIONAL: COLORS.BLACK,
  SECONDARY_TEXT: COLORS.ALMOST_BLACK,
};
